Add missing eslint configuration
fixing

 => ERROR [base 8/8] RUN pnpm build                                                                                                                                                                                                                                 0.9s
------
 > [base 8/8] RUN pnpm build:
0.480
0.480 > starter@ build /app
0.480 > vite build
0.480
0.719 vite v5.4.8 building for production...
0.856 transforming...
0.872 ✓ 4 modules transformed.
0.873 x Build failed in 139ms
0.873 error during build:
0.873 [vite-plugin-eslint] No ESLint configuration found in /app/src/apps/andalusia-forecast.
0.873 file: /app/src/apps/andalusia-forecast/app.ts
0.873     at CascadingConfigArrayFactory._finalizeConfigArray (/app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:4000:19)
0.873     at CascadingConfigArrayFactory.getConfigArrayForFile (/app/node_modules/.pnpm/@eslint+eslintrc@2.1.4/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3791:21)
0.873     at CLIEngine.isPathIgnored (/app/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/cli-engine/cli-engine.js:1000:18)
0.873     at ESLint.isPathIgnored (/app/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/eslint/eslint.js:681:26)
0.873     at Object.transform (file:///app/node_modules/.pnpm/vite-plugin-eslint@1.8.1_eslint@8.57.0_vite@5.4.8_@types+node@18.19.41_sass@1.77.8_/node_modules/vite-plugin-eslint/dist/index.mjs:1:1868)
0.873     at file:///app/node_modules/.pnpm/rollup@4.22.4/node_modules/rollup/dist/es/shared/node-entry.js:19936:40
0.873     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0.884  ELIFECYCLE  Command failed with exit code 1.
------
Dockerfile:18
--------------------
  16 |     # should be enabled in production deployment image build
  17 |     # RUN pnpm install --frozen-lockfile
  18 | >>> RUN pnpm build
  19 |
  20 |     FROM nginx:alpine3.19
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm build" did not complete successfully: exit code: 1